# Generated by Django 6.0.7 on 2026-07-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('simages', models.ImageField(default='default.webp', upload_to='uploads/')),
            ],
        ),
    ]
